[tool.poetry]
name        = "my-package"
version     = "0.1.0"
description = "description of the package"
license     = "MIT"

authors     = [
    "Ichigo Kurosaki <ichigo@bleach.com>"
]

readme      = "README.md"
repository  = "https://github.com/<project_path>"
homepage    = "https://github.com/<project_path>"
keywords    = ["packaging", "poetry"]

[tool.poetry.dependencies]
python      = "~2.7 || ^3.2" # compatible python versions
toml        = "^0.9"
# dependencies with extras
requests    = { version = "^2.13", extras = [ "security" ] }
# python specific dependencies with pre-realeases allowed
pathlib2    = { version = "^2.2", python = "~2.7", allow-prereleases = true }
# git dependencies
cleo        = { git = "https://github.com/sdispater/cleo.git", branch = "master" }
# optional dependencies (extras)
pendulum    = { version = "^1.4", optional = true }

[tool.poetry.dev-dependencies]
pytest      = "^3.0"
pytest-cov  = "^2.4"

[tool.poetry.scripts]
my-script   = "my_package:main"