---
# author    https://github.com/iroshanvidanage
# date      08/18/2024

stages:
  - test
  - build
  - deploy

image: python:3.8.0-slim

lint_test:
  stage: test
  before-script:
    - pip3 install flake8-html -y
  script:
    - flake8 --format=html --htmldir=flake_reports/
  artifacts:
    when: always # to store reports even if the job fails
    paths:
      - flake_reports/
    expire_in: "2 days"

pytest:
  stage: test
  before-script:
    - pip3 install pytest-html
    - pip3 install -r requirements.txt
  script:
    - pytest --html=pytest_reports/pytest_report.html --self-contained-html
  artifacts:
    when: always
    paths:
      - pytest_reports/
