---
# author    https://github.com/iroshanvidanage
# date      08/18/2024

stages:
  - test
  - build
  - deploy_staging

variables:
  PYTHON_IMAGE: python:3.8.0-slim
  DOCKER_IMAGE: docker:latest
  IMAGE_TAG: $CI_REGISTRY_IMAGE/employee-image:$CI_COMMIT_REF_SLUG
  STAGING_URL: [app_in_heroku]
  HEROKU_STAGING: registry.heroku.com/$STAGING_URL/web
  

# image: python:3.8.0-slim

lint_test:
  image: $PYTHON_IMAGE
  stage: test
  before-script:
    - pip3 install flake8-html -y
  script:
    - flake8 --format=html --htmldir=flake_reports/
  artifacts:
    when: always # to store reports even if the job fails
    paths:
      - flake_reports/
    expire_in: "2 days"

pytest:
  image: $PYTHON_IMAGE
  stage: test
  before-script:
    - pip3 install pytest-html
    - pip3 install -r requirements.txt
  script:
    - pytest --html=pytest_reports/pytest_report.html --self-contained-html
  artifacts:
    when: always
    paths:
      - pytest_reports/

build:
  image: $DOCKER_IMAGE
  services:
    - docker:dind
  stage: build
  before-script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker images
    - docker push $IMAGE_TAG

deploy_staging:
  image: $DOCKER_IMAGE
  services:
    - docker:dind
  stage: deploy_staging
  before-script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ducker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $HEROKU_STAGING
    - docker login -u _ -p $HEROKU_STAGING_API_KEY registry.heroku.com
    - docker push $HEROKU_STAGING
    # Can add the following codes or add another job for the releasing app to heroku
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_STAGING_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $STAGING_URL
    - echo "App deployed to staging server at https://$STAGING_URL.herokuapp.com/"

# the following job can be added additionally for heroku release
release_staging:
  image: node:latest
  stage: deploy_staging
  before-script:
    - npm install -g heroku
  script:
    - HEROKU_API_KEY=$HEROKU_STAGING_API_KEY heroku container:release web --app $STAGING_URL
    - echo "App deployed to staging server at https://$STAGING_URL.herokuapp.com/"
  need:
    - job: deploy_staging
      artifacts: false
  when: manual
